// data.js
export const items = [
    { id: 1, name: 'Acid Reflux' },
    { id: 2, name: 'Alcohol Dependence' },
    { id: 3, name: 'Allergies' },
    { id: 4, name: 'Anti-bacterial' },
    { id: 5, name: 'Anti-fungal' },
    { id: 6, name: 'Anti-Inflammation' },
    { id: 7, name: 'Anti-viral' },
    { id: 8, name: 'Bone Health' },
    { id: 9, name: 'Cancer Prevention' },
    { id: 10, name: 'Cardiovascular Health' },
    { id: 11, name: 'Cholesterol Management' },
    { id: 12, name: 'Diabetes Control' },
    { id: 13, name: 'Digestive Health' },
    { id: 14, name: 'Energy Boost' },
    { id: 15, name: 'Eye Health' },
    { id: 16, name: 'Hair Growth' },
    { id: 17, name: 'Heartburn Relief' },
    { id: 18, name: 'Immune Support' },
    { id: 19, name: 'Joint Health' },
    { id: 20, name: 'Liver Detox' },
    { id: 21, name: 'Mental Clarity' },
    { id: 22, name: 'Muscle Recovery' },
    { id: 23, name: 'Pain Relief' },
    { id: 24, name: 'Respiratory Health' },
    { id: 25, name: 'Skin Care' },
    { id: 26, name: 'Stress Management' },
    { id: 27, name: 'Weight Loss' },
    { id: 28, name: 'Asthma Control' },
    { id: 29, name: 'Arthritis Relief' },
    { id: 30, name: 'Osteoporosis Prevention' },
    { id: 31, name: 'Antioxidant Support' },
    { id: 32, name: 'Memory Enhancement' },
    { id: 33, name: 'Digestive Enzymes' },
    { id: 34, name: 'Blood Pressure Regulation' },
    { id: 35, name: 'Kidney Health' },
    { id: 36, name: 'Hair Care' },
    { id: 37, name: 'Detoxification' },
    { id: 38, name: 'Anti-aging' },
    { id: 39, name: 'Hormone Balance' },
    { id: 40, name: 'Probiotics' },
    { id: 41, name: 'Hair Loss Prevention' },
    { id: 42, name: 'Vision Improvement' },
    { id: 43, name: 'Metabolism Boost' },
    { id: 44, name: 'Inflammatory Bowel Disease Management' },
    { id: 45, name: 'Thyroid Health' },
    { id: 46, name: 'Cognitive Function Enhancement' },
    { id: 47, name: 'Gut Health' },
    { id: 48, name: 'Energy Efficiency' },
    { id: 49, name: 'Anxiety Relief' },
    { id: 50, name: 'Mood Enhancement' },
    { id: 51, name: 'Bone Density' },
    { id: 52, name: 'Hydration' },
    { id: 53, name: 'Protein Intake' },
    { id: 54, name: 'Brain Health' },
    { id: 55, name: 'Dental Care' },
    { id: 56, name: 'Acne Treatment' },
    { id: 57, name: 'Hair Color Enhancement' },
    { id: 58, name: 'Vision Protection' },
    { id: 59, name: 'Hangover Relief' },
    { id: 60, name: 'Stomach Ulcer Prevention' },
    { id: 61, name: 'Blood Sugar Control' },
    { id: 62, name: 'Lung Health' },
    { id: 63, name: 'Nail Strength' },
    { id: 64, name: 'Heart Health' },
    { id: 65, name: 'Throat Soothing' },
    { id: 66, name: 'Liver Support' },
    { id: 67, name: 'Aromatherapy' },
    { id: 68, name: 'All-Natural Skincare' },
    { id: 69, name: 'Weight Gain' },
    { id: 70, name: 'Digestive Cleansing' },
    { id: 71, name: 'Stress Reduction' },
    { id: 72, name: 'Cognitive Enhancement' },
    { id: 73, name: 'Heart Disease Prevention' },
    { id: 74, name: 'Healthy Aging' },
    { id: 75, name: 'Vision Correction' },
    { id: 76, name: 'Joint Flexibility' },
    { id: 77, name: 'Hair Thickening' },
    { id: 78, name: 'Skin Hydration' },
    { id: 79, name: 'Prostate Health' },
    { id: 80, name: 'Colon Health' },
    { id: 81, name: 'Brain Function Optimization' },
    { id: 82, name: 'Detox Diet' },
    { id: 83, name: 'Anti-Stress' },
    { id: 84, name: 'Blood Circulation Improvement' },
    { id: 85, name: 'Digestive Regularity' },
    { id: 86, name: 'Injury Recovery' },
    { id: 87, name: 'Skin Brightening' },
    { id: 88, name: 'Chronic Pain Management' },
    { id: 89, name: 'Energy Elevation' },
    { id: 90, name: 'Cough Relief' },
    { id: 91, name: 'Bladder Health' },
    { id: 92, name: 'Blood Clot Prevention' },
    { id: 93, name: 'Anemia Treatment' },
    { id: 94, name: 'Hygiene Enhancement' },
    { id: 95, name: 'Fatigue Reduction' },
    { id: 96, name: 'Nerve Health' },
    { id: 97, name: 'Tooth Sensitivity' },
    { id: 98, name: 'Calorie Control' },
    { id: 99, name: 'Digestive Balance' },
    { id: 100, name: 'Wound Healing' },
];